# NumPy

## 1. Installation
```bash
pip install numpy
```
If you are using Anaconda/Miniconda, NumPy is usually installed by default.

## 2. Importing NumPy

In [1]:
import numpy as np
np.__version__

'1.21.5'

## 3. Creating Arrays

In [4]:
# From Python lists
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([[1, 2, 3], [4, 5, 6]])
print('arr1:', arr1)
print('arr2:\n', arr2)

# Using built‑in helpers
zeros = np.zeros((2, 3)) # tuple, two dimension
zeros_1 = np.zeros(4,) # int, one dimension
ones  = np.ones((2, 3))
identity = np.eye(3)
arange  = np.arange(0, 10, 2)
lin = np.linspace(0, 1, 5)

print('zeros:\n', zeros)
print('ones:\n', ones)
print('zeros_1',zeros_1)
print('identity:\n', identity)
print('arange:', arange)
print('linspace:', lin)

arr1: [1 2 3]
arr2:
 [[1 2 3]
 [4 5 6]]
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
zeros_1 [0. 0. 0. 0.]
identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


### 3.1 Array Attributes

In [5]:
print('Shape:', arr_2.shape)
print('Datatype:', arr_2.dtype)
print('Size:', arr_2.size)
print('Dimension (ndim):', arr_2.ndim)

Shape: (2, 3)
Datatype: int32
Size: 6
Dimension (ndim): 2


## 4. Basic Operations

In [6]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print('Element‑wise add :', a + b)
print('Element‑wise mul :', a * b)
print('Scalar add      :', a + 5)
print('Scalar mul      :', b * 10)

# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print('Matrix product  :\n', A @ B)

Element‑wise add : [11 22 33]
Element‑wise mul : [10 40 90]
Scalar add      : [15 25 35]
Scalar mul      : [10 20 30]
Matrix product  :
 [[19 22]
 [43 50]]


## 5. Indexing & Slicing

In [7]:
C = np.arange(1, 13).reshape(3, 4)
print('C:\n', C)
print('First row      :', C[0])
print('First column   :', C[:, 0])
print('Sub‑matrix 2x2 :\n', C[1:, 1:3])

C:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row      : [1 2 3 4]
First column   : [1 5 9]
Sub‑matrix 2x2 :
 [[ 6  7]
 [10 11]]


## 6. Broadcasting

In [8]:
D = np.ones((3, 3))
print('Original D:\n', D)
D + np.array([1, 2, 3])   # row vector broadcasted

Original D:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

## 7. Useful Functions

In [9]:
rng = np.random.default_rng(0)
rand = rng.random((2, 2))
print('Random 2x2:\n', rand)

print('Sum  :', rand.sum())
print('Mean :', rand.mean())
print('Std  :', rand.std())

Random 2x2:
 [[0.63696169 0.26978671]
 [0.04097352 0.01652764]]
Sum  : 0.9642495605500484
Mean : 0.2410623901375121
Std  : 0.24900439287469212


### 7.1 Reshape & Flatten

In [10]:
E = np.arange(8)
print('E:', E)
print('E reshaped 2x4:\n', E.reshape(2, 4))
print('Flatten back  :', E.reshape(2, 4).ravel())

E: [0 1 2 3 4 5 6 7]
E reshaped 2x4:
 [[0 1 2 3]
 [4 5 6 7]]
Flatten back  : [0 1 2 3 4 5 6 7]


## 8. Basic Linear Algebra

In [11]:
X = np.array([[1, 2], [3, 4]])
print('det(X)  :', np.linalg.det(X))
print('inv(X)  :\n', np.linalg.inv(X))
print('eig(X)  :', np.linalg.eig(X)[0])

det(X)  : -2.0000000000000004
inv(X)  :
 [[-2.   1. ]
 [ 1.5 -0.5]]
eig(X)  : [-0.37228132  5.37228132]
